package it.danilo.projectwork.entity;
// Generated 3 lug 2024, 21:37:11 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "project_work")
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private Set<Status> statuses = new HashSet<Status>(0);
	private Set<District> districts = new HashSet<District>(0);
	private Set<Device> devices = new HashSet<Device>(0);

	public City() {
	}

	public City(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public City(Integer id, String name, String password, Set<Status> statuses, Set<District> districts, Set<Device> devices) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.statuses = statuses;
		this.districts = districts;
		this.devices = devices;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Status> getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set<Status> statuses) {
		this.statuses = statuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

}
