package it.danilo.projectwork.entity;
// Generated 3 lug 2024, 21:37:11 by Hibernate Tools 5.2.13.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district", catalog = "project_work", uniqueConstraints = @UniqueConstraint(columnNames = { "id_city",
		"address" }))
public class District implements java.io.Serializable {

	private Integer id;
	private City city;
	private String address;
	private Set<Device> devices = new HashSet<Device>(0);
	private Set<Status> statuses = new HashSet<Status>(0);

	public District() {
	}

	public District(City city, String address) {
		this.city = city;
		this.address = address;
	}

	public District(Integer id, City city, String address, Set<Device> devices, Set<Status> statuses) {
		this.id = id;
		this.city = city;
		this.address = address;
		this.devices = devices;
		this.statuses = statuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_city", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Status> getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set<Status> statuses) {
		this.statuses = statuses;
	}

}
