package it.danilo.projectwork.entity;
// Generated 3 lug 2024, 21:37:11 by Hibernate Tools 5.2.13.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.Version;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "project_work")
public class Status implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private City city;
	private Device device;
	private District district;
	private int co2Level;

	public Status() {
	}

	public Status(City city, Device device, District district, int co2Level) {
		this.city = city;
		this.device = device;
		this.district = district;
		this.co2Level = co2Level;
	}

	public Status(Integer id, City city, Device device, District district, int co2Level) {
		this.id = id;
		this.city = city;
		this.device = device;
		this.district = district;
		this.co2Level = co2Level;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.DATE)
	@Column(name = "timestamp", nullable = false, length = 10)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_city", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_device", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_district", nullable = false)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Column(name = "co2_level", nullable = false)
	public int getCo2Level() {
		return this.co2Level;
	}

	public void setCo2Level(int co2Level) {
		this.co2Level = co2Level;
	}

}
